/** Declaration file generated by dts-gen */

export = alea;

declare function alea(...args: any[]): any;

declare namespace alea {
    const prototype: {
    };

    function importState(i: any): any;

    namespace importState {
        const prototype: {
        };

    }

}

